# Generated by Django 4.2.2 on 2023-06-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='squad_abbr',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
